mongodb.config:
   localhostconn:
      host:localhost
      port:27017
      datadb:local
      #fixeddb:spider_url_fixed
      #tempdb:spider_url_temp
   180conn:
      host:192.168.1.180
      port:27017
      datadb:spider_data
      fixeddb:spider_url_fixed
      tempdb:spider_url_temp
   69conn:
      host:172.22.69.35
      port:20000
      datadb:spider_data
      fixeddb:spider_url_fixed
      tempdb:spider_url_temp
   69.41conn:
      host:172.22.69.41
      port:27017
      datadb:spider_data
      fixeddb:spider_url_fixed
      tempdb:spider_url_temp

mysql.config:
   localhostconn:
      host:localhost
      port:3306
      db:chatbot
      user:root
      password:root
      charset:utf8
   222conn:
      host:192.168.1.222
      port:3306
      db:jep
      user:root
      password:123456
      charset:utf8
   43conn:
      host:172.22.69.43
      port:3306
      db:spider
      user:spider
      password:spider#O2018
      charset:utf8
   41conn:
     host:172.22.69.41
     port:3306
     db:ai-training
     user:root
     password:dev007%P
     charset:utf8
   41conn_test:
     host:172.22.69.41
     port:3306
     db:spider_test
     user:root
     password:dev007%P
     charset:utf8
   67.25conn:
     host:172.22.67.25
     port:3306
     db:spider
     user:root
     password:Code123!@#
     charset:utf8
   67.25connai:
     host:172.22.67.25
     port:3306
     db:ai-training
     user:root
     password:Code123!@#
     charset:utf8
   48conn:
     host:172.22.69.48
     port:3306
     db:ijep_chatbot
     user:root
     password:dev007%P
     charset:utf8